apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: aum-thakkar/${{ values.app_name }}.git
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental



  